pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=main
      - check-success=gitStream workflow automation
    actions:
      merge:
        method: merge

queue_rules:
  - name: default
    queue_conditions:
      - check-success=gitStream workflow automation